---
apiVersion: v1
kind: Service
metadata:
  name: argocd
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: argocd
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
  loadBalancerClass: tailscale
---


